### ISSUE TITLE
[Issue] dispensersTiltSoil doesn't update the block it tilts

### ISSUE THREAD

**Issue by Cypphi** [gnembon/carpet-extra#174]
The title, if you tilt a block with a dispenser while there's a block above the dirt it still tilts it

**Comment by DragonEggBedrockBreaking** [comment]
1) Can confirm this bug, and actually, if you manually give the soil (with a block above it) a block update, e.g. by placing a block next to it, it will still not update; it will only update when you remove the block on top of it then re-place it manually (on top). This seems to suggest that soil doesn't update in many cases in vanilla, because Mojang probably thought it would be useless, because placing a block on top of it should update it in vanilla anyway, which should be enough with vanilla behaviour. Seems that carpet's behaviour is a new case which was (naturally) not accounted for in vanilla code, so new update code is probably necessary for tilled soil, because from what I can see, the carpet code just checks whether the block **can** become farmland, then tills it.

2) It's 'till', not 'tilt' (sorry, spelling errors sometimes trigger me quite a bit)

**Comment by gnembon** [comment]
https://github.com/gnembon/carpet-extra/pull/212
