### ISSUE TITLE
Sneaking on Scaffolding?

### ISSUE THREAD

**Issue by TimelyToga** [gnembon/carpet-extra#202]
While building red stone contraptions in Survival, it is frequently required to hold Shift to place a component against a component with an inventory (Hopper / dropper / *Crafting Table* etc) which leads to a chaotic mess when bridging around with Scaffolding.

My hypothetical fix would be to allow a custom hotkey to delineate between shift placing / crouching and Shift-descending while standing on / in scaffolding. 

I am willing to contribute code, but I'm wondering if this is a feature that would fit well as a carpet-extra / carpet extension, or as it's own standalone mod? Also if anyone has critiques of this concept, please do leave me a comment here~

**Comment by altrisi** [comment]
I'd say as a standalone mod/extension, since Carpet/Extra rules are expected to work without the need of the mod client-side if on a server, with the sole exception being very minor things (e.g. `cleanLogs`) or the `accurateBlockPlacement` (that is actually cheating on that by being defined as "a protocol to provide clients ways to place blocks differently", without actually implementing such protocol here by itself), still having the must to be compatible with vanilla clients. This, as you said, would require a new hotkey client-side, so I'd go for either a standalone mod or an extension, the one you like the most.

If you go for an extension, you already have a settings manager implementation in case you want to provide multiple settings, and also have a protocol to send data between client and server (the Carpet Protocol in base Carpet).

If you go for a mod, well, you can do anything you want really, though of course you would need to implement your own way to sync with the server if you need to (I think FAPI has some helpers for that, also for custom keybinds) or any settings.

The concept is actually quite good, I'd definitely try it, not sure how long I'd take to get used to another hotkey but I'd certainly be useful.

**Comment by TimelyToga** [comment]
Thanks for the writeup :) I'll take a crack at writing an extension and then try a standalone mod if necessary~

**Comment by TimelyToga** [comment]
Closing as my query was answered

**Comment by altrisi** [comment]
Just wondering, did you end up making it?
