### ISSUE TITLE
crashes bigger sponge absorption radius

### ISSUE THREAD

**Issue by xXRinzlerrXx** [gnembon/carpet-extra#300]
minecraft 1.20.1 + fabric 0.14.21 + fabric api 0.84.0 + collective v 6.62 + Carpet 1.4.112 + Carpet Extra 1.4.115
crashes when running with biggerspongeabsorptionradius-1.20.1-3.1

on 1.19.4 everything worked fine

**Comment by altrisi** [comment]
May be because Carpet Extra has a rule for giving sponges a bigger radius (`maxSpongeRange` and `maxSpongeSuck`).

A crash report would be helpful anyway.

**Comment by altrisi** [comment]
I'll close this for now, if it's still an issue for you just comment with the crash report and I'll reopen it to see if there's anything that can be done in this side (though likely you can just use the rule from Carpet Extra).

**Comment by DefinitelyNotFred** [comment]
I have the same problem. See [latest.log](https://github.com/user-attachments/files/16276553/latest.log) for a crash report.

If you take out one of either mod but leave in their dependencies it doesn't produce a crash, so it really is a problem between Bigger Sponge Absorption Radius and Carpet Extras in particular.

By the way, BSAR isn't quite what it sounds like. Instead of increasing the radius of individual sponges, it instead makes it so placing multiple sponges around the same point makes those sponges act as a single giant sponge whose radius can increase far beyond the range of a normally placed sponge. That makes for a far more interesting mechanic than a simple radius increase. [Link to mod page.](https://modrinth.com/mod/bigger-sponge-absorption-radius)

**Comment by DefinitelyNotFred** [comment]
I should mention that, for whatever reason, this mod combination does not produce a crash report file, so the latest log file is the best I can offer.
